# Generated by Django 3.0.5 on 2020-05-06 00:00

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Time when instance was created.', verbose_name='create time')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Time when instance was deleted.', null=True, verbose_name='delete time')),
                ('last_update_at', models.DateTimeField(auto_now=True, help_text='Time when isinstance was updted.', null=True, verbose_name='last update')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', user.models.UserManager()),
            ],
        ),
    ]
