# Generated by Django 3.0.5 on 2020-05-06 00:00

from django.db import migrations, models
import uploads.helpers
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Time when instance was created.', verbose_name='create time')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Time when instance was deleted.', null=True, verbose_name='delete time')),
                ('last_update_at', models.DateTimeField(auto_now=True, help_text='Time when isinstance was updted.', null=True, verbose_name='last update')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Media unique code.', primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=200)),
                ('data', models.FileField(max_length=500, upload_to=uploads.helpers.user_directory_path)),
            ],
            options={
                'verbose_name': 'upload',
                'verbose_name_plural': 'uploads',
            },
        ),
    ]
